controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController #joint_effort_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    cartesian_motion_handle:
      type : cartesian_controller_handles/MotionControlHandle

    
joint_trajectory_controller:
  ros__parameters:
    #state_publish_rate: 500.
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

joint_group_velocity_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

cartesian_motion_controller:
    ros__parameters:
      end_effector_link: "panda_link8"
      robot_base_link: "panda_link0"
      target_frame_topic: "target_frame"
      solver:
        #error_scale: 1.0
        iterations: 1
      pd_gains:
          trans_x: {p: 200.0, d: 10.0}
          trans_y: {p: 200.0, d: 10.0}
          trans_z: {p: 200.0, d: 10.0}
          rot_x: {p: 50.0, d: 10.0}
          rot_y: {p: 50.0, d: 10.0}
          rot_z: {p: 50.0, d: 10.0}
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
      command_interfaces:
        - velocity
      state_interfaces:
        - position
        - velocity

cartesian_motion_handle:
    ros__parameters:
      end_effector_link: "panda_link8"
      robot_base_link: "panda_link0"
      target_frame_topic: "target_frame"
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
      state_interfaces:
        - position
        - velocity