controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController #joint_effort_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      
# Test package 'cartesian_controllers"'
    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController
    cartesian_motion_handle:
      type : cartesian_controller_handles/MotionControlHandle
    cartesian_force_controller:
      type: "cartesian_force_controller/CartesianForceController"
    cartesian_compliance_controller:
      type: "cartesian_compliance_controller/CartesianComplianceController"

    
joint_trajectory_controller:
  ros__parameters:
    #state_publish_rate: 500.
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

joint_group_velocity_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

cartesian_motion_controller:
    ros__parameters:
      end_effector_link: "panda_ft_sensor"
      robot_base_link: "panda_link0"
      target_frame_topic: "target_frame"
      target_twist_topic: "target_twist"
      solver:
        error_scale: 1.0
        iterations: 1
      pd_gains:
          trans_x: {p: 600.0, d: 40.0}
          trans_y: {p: 600.0, d: 40.0}
          trans_z: {p: 600.0, d: 40.0}
          rot_x: {p: 100.0, d: 20.0}
          rot_y: {p: 100.0, d: 20.0}
          rot_z: {p: 100.0, d: 20.0}
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
      command_interfaces:
        - velocity
      state_interfaces:
        - position
        - velocity

cartesian_motion_handle:
    ros__parameters:
      end_effector_link: "panda_ft_sensor"
      robot_base_link: "panda_link0"
      target_frame_topic: "target_frame"
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
      state_interfaces:
        - position
        - velocity


cartesian_force_controller:
    ros__parameters:
      end_effector_link: "panda_ft_sensor"
      robot_base_link: "panda_link0"      
      ft_sensor_ref_link: "panda_ft_sensor"
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
      command_interfaces:
        - velocity
      state_interfaces:
        - position
        - velocity
      pd_gains:
          trans_x: {p: 0.1}
          trans_y: {p: 0.1}
          trans_z: {p: 0.1}
          rot_x: {p: 0.0}
          rot_y: {p: 0.0}
          rot_z: {p: 0.0}


cartesian_compliance_controller:
    ros__parameters:
      end_effector_link: "panda_ft_sensor"
      robot_base_link: "panda_link0"     
      ft_sensor_ref_link: "panda_ft_sensor"
      compliance_ref_link: "panda_ft_sensor"
      target_frame_topic: "target_frame"
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
      command_interfaces:
        - velocity
      state_interfaces:
        - position
        - velocity

      stiffness:  # w.r.t. compliance_ref_link
          trans_x: 500.0
          trans_y: 500.0
          trans_z: 50.0
          rot_x: 200.0
          rot_y: 200.0
          rot_z: 200.0

      pd_gains:
          trans_x: {p: 1.0}
          trans_y: {p: 1.0}
          trans_z: {p: 0.5}
          rot_x: {p: 0.05}
          rot_y: {p: 0.05}
          rot_z: {p: 0.05}